config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  devise_for :users, controllers: { sessions: 'users/sessions',confirmations: 'users/confirmations' }
  root "home#index"
  get '/user/blog' => "blogs#userblog" , as: "user_blog"
  post '/blogs/:id/comment' => "comment#create" ,as: "create_comment"
  delete '/comments/:id' => "comment#destroy" , as: "comment"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ""
 validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
 belongs_to :user
 has_many :comments
 validates :title, presence: true
 validates :content, presence: true

 def self.search (name)
   if name

    where(["title LIKE ? and status ='public'","%#{name}%"]).order(created_at: :desc)
   else
     where(["status = 'public'"]).order(created_at: :desc)

   end
 end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:edit,:new,:destroy,:create,:userblog]
  before_action :set_breadcrum, only:[:new,:userblog]
  before_action :check_user, only:[:edit]

  # GET /blogs
  # GET /blogs.json
  def index
    if user_signed_in?
      redirect_to user_blog_path
    else
      redirect_to root_path
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if (@blog.status == "private" )
      check_user
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @newblog = "active"
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create

    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

      respond_to do |format|
        if @blog.save
          format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
          format.json { render :show, status: :created, location: @blog }
        else
          format.html { render :new }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to user_blog_path, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def userblog
    @blogs = current_user.blogs
    @myblog ="active"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def check_user
      if user_signed_in?
        if @blog.user_id.to_i != current_user.id
            redirect_to root_path
        end
      else
          redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
    params.require(:blog).permit(:title, :content,:status,:avatar )
    end
    def set_breadcrum
      @newblog = nil
      @myblog = nil
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>


<%= form_for @blog, html: { multipart: true } do |f| %>
  <p class ="from-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class=>"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content,:class=>"form-control",:id=>"summernote" %>
  </p>
  <p class="form-group">
    <%=f.label :status %>
    <br>
    <%= f.select :status, options_for_select([["public"], ["private"]]),:class=>"form-control" %>

  </p>
  <div class="">
    <%= f.file_field :avatar %>
  </div>


    <%= f.submit "Submit", :class =>"choose-file"%>

<% end %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

<script type="text/javascript">
$(document).ready(function() {
  $('#summernote').summernote({

    height: 300,                 // set editor height
  minHeight: null,             // set minimum height of editor
  maxHeight: null,             // set maximum height of editor
  focus: true                  // set focus to editable area after initializing summernote
  });
});
</script>

app/views/blogs/new.html.erb
<h1>New Blog</h1>


<%= form_for :blog, url:blogs_path, html: { multipart: true } do |f| %>
  <p class ="from-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class=>"form-control" %>
  </p>

  <p class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content,:class=>"form-control",:id=>"summernote" %>
  </p>
  <p class="form-group">
    <%=f.label :status %>
    <br>
    <%= f.select :status, options_for_select([["public"], ["private"]]),:class=>"form-control" %>
  </p>

  <div >
    <%= f.file_field :avatar  %>
  </div>



<div class="">
  <%= f.submit "Submit", :class =>"choose-file"%>
</div>


<% end %>


<%= link_to 'Back', blogs_path %>
<script type="text/javascript">
$(document).ready(function() {
  $('#summernote').summernote({

    height: 300,                 // set editor height
  minHeight: null,             // set minimum height of editor
  maxHeight: null,             // set maximum height of editor
  focus: true                  // set focus to editable area after initializing summernote
  });
});
</script>

app/views/blogs/show.html.erb
<div class="title">
  <h1 class ="title"> <%=@blog.title%> </h1>
  <p>Post by: <%=@blog.user.email%></p>
</div>

<div class="blogimg">
<%if @blog.avatar.url != "" %>
  <%= image_tag @blog.avatar.url %>
  <%end%>
</div>
<div class="content" >
  <%= @blog.content.html_safe %>
</div>

<%if user_signed_in? and current_user.id == @blog.user.id%>
<%= link_to 'Edit', edit_blog_path(@blog) %>
<%end%>
<%= link_to 'Back To Home', root_path %>
<h3>Comment:</h3>

    <%@blog.comments.each do |comment|%>
        <div class="panel panel-default">
          <div class="panel-heading">
            <%if user_signed_in? && comment.user.id == current_user.id%><!-- /panel-body -->
          <div style ="float:right">
            <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          <%end%>
            <strong><%=comment.user.email%></strong> <span class="text-muted"><%=comment.post_date.strftime('%d/%m/%y')%></span>
          </div>
          <div class="panel-body">
            <%=comment.content%>
            </div>

          </div><!-- /panel panel-default -->
    <%end%>

<%if user_signed_in?%>
<div class="addcoment">
  <p><%=current_user.email%></p>
  <%= form_for :comment, url:create_comment_path do |f| %>
    <p class="form-group">
      <%= f.text_area :content,:class=>"form-control" %>
    </p>
      <%= f.submit "Submit", :class =>"btn btn-default"%>
  <% end %>

</div>
<%end%>

app/views/blogs/userblog.html.erb
<p id="notice"><%= notice %></p>

<% @blogs.each do |blog| %>
<div class="mycontainer">
  <%= image_tag blog.avatar.url(:thumb) %>
  <p>Title: <%=blog.title%> </p>
  <spanp>Status: <%=blog.status%></span>
  <span><%= link_to 'Read more', blog%></span>
  <span><%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' } %></span>
</div>
<% end %>