config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  devise_for :users, controllers: { sessions: 'users/sessions',confirmations: 'users/confirmations' }
  root "home#index"
  get '/user/blog' => "blogs#userblog" , as: "user_blog"
  post '/blogs/:id/comment' => "comment#create" ,as: "create_comment"
  delete '/comments/:id' => "comment#destroy" , as: "comment"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_topmenu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%=link_to "Home",root_path,:class=>"navbar-brand " %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%=@newblog%>"><%=link_to "New Blog",new_blog_path%></li>
      </ul>
      <form class="navbar-form navbar-left" action = "/">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="name">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?%>
        <li class="<%=@myblog%>"><%=link_to "My Blog",user_blog_path,:class=>"#{@myblog}"%></li>
        <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          </ul>
          <%else%>
          <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Guess<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li ><%= link_to('Sign up', new_user_registration_path)%></li>
            <li><%= link_to('Login', new_user_session_path)  %></li>
          </ul>

          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>